In [6]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [7]:
# create a new dataframe based on the past 15 weeks
df_past_10 = pd.DataFrame({ "Tall_1": [0,0,0,0,0,0,0,0,0,0,0,0,0,1,0],
                            "Tall_2": [0,0,0,0,1,0,1,0,0,0,0,0,0,0,0],
                            "Tall_3": [1,0,0,0,0,1,0,0,0,0,0,1,0,0,0],
                            "Tall_4": [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
                            "Tall_5": [0,0,0,0,1,0,0,0,0,0,0,0,0,0,0],
                            "Tall_6": [0,0,0,0,0,0,0,0,0,0,0,0,1,0,1],
                            "Tall_7": [0,1,0,1,0,0,0,0,0,0,0,0,1,0,0],
                            "Tall_8": [0,0,0,0,0,0,0,0,1,0,0,0,0,0,0],
                            "Tall_9": [0,0,1,0,0,1,0,0,0,0,0,0,0,0,0],
                           "Tall_10": [0,0,0,0,0,0,0,0,1,0,1,0,0,0,0],
                           "Tall_11": [0,1,0,0,0,0,1,0,0,0,0,0,0,0,0],
                           "Tall_12": [0,0,0,0,0,0,1,0,0,0,0,0,0,0,1],
                           "Tall_13": [0,0,0,0,0,0,0,0,0,0,0,0,1,0,0],
                           "Tall_14": [0,0,0,0,0,1,0,0,0,0,0,0,0,1,0],
                           "Tall_15": [1,0,0,0,0,0,0,1,0,0,1,1,0,0,0],
                           "Tall_16": [0,0,1,0,0,1,0,0,0,0,0,0,0,0,0],
                           "Tall_17": [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
                           "Tall_18": [0,1,0,0,0,0,0,0,0,0,0,0,1,0,0],
                           "Tall_19": [0,0,0,0,0,0,0,0,0,0,0,0,1,0,0],
                           "Tall_20": [0,0,0,0,0,1,0,0,0,0,0,1,0,0,0],
                           "Tall_21": [0,1,0,0,0,0,0,1,0,0,0,0,0,0,0],
                           "Tall_22": [0,0,0,0,0,0,0,0,0,0,0,0,0,0,1],
                           "Tall_23": [0,0,0,0,0,0,1,0,0,0,0,0,1,0,1],
                           "Tall_24": [0,0,0,0,0,0,0,0,0,0,0,0,0,0,1],
                           "Tall_25": [1,0,0,0,0,0,0,1,0,0,0,1,0,1,0],
                           "Tall_26": [0,0,0,0,0,0,1,0,0,0,0,0,0,0,0],
                           "Tall_27": [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
                           "Tall_28": [0,0,0,0,0,0,0,0,0,0,1,0,0,1,0],
                           "Tall_29": [0,0,1,0,0,0,0,0,0,1,0,1,0,0,0],
                           "Tall_30": [0,0,0,0,0,0,0,0,0,1,0,0,0,0,0],
                           "Tall_31": [0,0,1,0,0,0,0,0,0,1,0,0,0,0,0],
                           "Tall_32": [0,0,0,1,0,0,0,1,0,0,0,0,0,0,0],
                           "Tall_33": [1,0,1,1,0,0,0,0,0,0,0,0,0,0,0],
                           "Tall_34": [1,1,0,0,0,0,0,1,0,0,0,0,0,0,0],
                           "Tall_35": [0,1,0,0,0,0,0,0,1,0,0,0,0,0,1],
                           "Tall_36": [0,0,0,1,0,0,0,0,0,1,0,1,0,0,0],
                           "Tall_37": [0,0,0,1,0,0,0,0,1,0,0,0,0,0,0],
                           "Tall_38": [0,0,0,0,0,0,0,0,1,0,0,0,0,1,0],
                           "Tall_39": [1,0,1,1,0,0,0,1,0,1,1,0,0,0,0],
                           "Tall_40": [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
                           "Tall_41": [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
                           "Tall_42": [0,0,0,0,1,0,0,0,1,0,0,0,0,0,0],
                           "Tall_43": [0,0,0,0,0,0,1,0,0,0,0,0,0,1,0],
                           "Tall_44": [0,0,0,0,1,1,0,0,0,1,1,0,0,0,0],
                           "Tall_45": [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
                           "Tall_46": [0,0,0,0,1,0,0,0,0,0,1,0,0,0,0],
                           "Tall_47": [0,0,0,0,1,0,0,0,0,0,0,0,0,0,0],
                           "Tall_48": [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]})
df_past_10.transpose()

         0  1  2  3  4  5  6  7  8  9  10  11  12  13  14
Tall_1   0  0  0  0  0  0  0  0  0  0   0   0   0   1   0
Tall_2   0  0  0  0  1  0  1  0  0  0   0   0   0   0   0
Tall_3   1  0  0  0  0  1  0  0  0  0   0   1   0   0   0
Tall_4   0  0  0  0  0  0  0  0  0  0   0   0   0   0   0
Tall_5   0  0  0  0  1  0  0  0  0  0   0   0   0   0   0
Tall_6   0  0  0  0  0  0  0  0  0  0   0   0   1   0   1
Tall_7   0  1  0  1  0  0  0  0  0  0   0   0   1   0   0
Tall_8   0  0  0  0  0  0  0  0  1  0   0   0   0   0   0
Tall_9   0  0  1  0  0  1  0  0  0  0   0   0   0   0   0
Tall_10  0  0  0  0  0  0  0  0  1  0   1   0   0   0   0
Tall_11  0  1  0  0  0  0  1  0  0  0   0   0   0   0   0
Tall_12  0  0  0  0  0  0  1  0  0  0   0   0   0   0   1
Tall_13  0  0  0  0  0  0  0  0  0  0   0   0   1   0   0
Tall_14  0  0  0  0  0  1  0  0  0  0   0   0   0   1   0
Tall_15  1  0  0  0  0  0  0  1  0  0   1   1   0   0   0
Tall_16  0  0  1  0  0  1  0  0  0  0   0   0   0   0   0
Tall_17  0  0  0  0  0  0  0  0  0  0   0   0   0   0   0
Tall_18  0  1  0  0  0  0  0  0  0  0   0   0   1   0   0
Tall_19  0  0  0  0  0  0  0  0  0  0   0   0   1   0   0
Tall_20  0  0  0  0  0  1  0  0  0  0   0   1   0   0   0
Tall_21  0  1  0  0  0  0  0  1  0  0   0   0   0   0   0
Tall_22  0  0  0  0  0  0  0  0  0  0   0   0   0   0   1
Tall_23  0  0  0  0  0  0  1  0  0  0   0   0   1   0   1
Tall_24  0  0  0  0  0  0  0  0  0  0   0   0   0   0   1
Tall_25  1  0  0  0  0  0  0  1  0  0   0   1   0   1   0
Tall_26  0  0  0  0  0  0  1  0  0  0   0   0   0   0   0
Tall_27  0  0  0  0  0  0  0  0  0  0   0   0   0   0   0
Tall_28  0  0  0  0  0  0  0  0  0  0   1   0   0   1   0
Tall_29  0  0  1  0  0  0  0  0  0  1   0   1   0   0   0
Tall_30  0  0  0  0  0  0  0  0  0  1   0   0   0   0   0
Tall_31  0  0  1  0  0  0  0  0  0  1   0   0   0   0   0
Tall_32  0  0  0  1  0  0  0  1  0  0   0   0   0   0   0
Tall_33  1  0  1  1  0  0  0  0  0  0   0   0   0   0   0
Tall_34  1  1  0  0  0  0  0  1  0  0   0   0   0   0   0
Tall_35  0  1  0  0  0  0  0  0  1  0   0   0   0   0   1
Tall_36  0  0  0  1  0  0  0  0  0  1   0   1   0   0   0
Tall_37  0  0  0  1  0  0  0  0  1  0   0   0   0   0   0
Tall_38  0  0  0  0  0  0  0  0  1  0   0   0   0   1   0
Tall_39  1  0  1  1  0  0  0  1  0  1   1   0   0   0   0
Tall_40  0  0  0  0  0  0  0  0  0  0   0   0   0   0   0
Tall_41  0  0  0  0  0  0  0  0  0  0   0   0   0   0   0
Tall_42  0  0  0  0  1  0  0  0  1  0   0   0   0   0   0
Tall_43  0  0  0  0  0  0  1  0  0  0   0   0   0   1   0
Tall_44  0  0  0  0  1  1  0  0  0  1   1   0   0   0   0
Tall_45  0  0  0  0  0  0  0  0  0  0   0   0   0   0   0
Tall_46  0  0  0  0  1  0  0  0  0  0   1   0   0   0   0
Tall_47  0  0  0  0  1  0  0  0  0  0   0   0   0   0   0
Tall_48  0  0  0  0  0  0  0  0  0  0   0   0   0   0   0

In [8]:
# recent frequency sum
df_past_10.sum()

Tall_1     1
Tall_2     2
Tall_3     3
Tall_4     0
Tall_5     1
Tall_6     2
Tall_7     3
Tall_8     1
Tall_9     2
Tall_10    2
Tall_11    2
Tall_12    2
Tall_13    1
Tall_14    2
Tall_15    4
Tall_16    2
Tall_17    0
Tall_18    2
Tall_19    1
Tall_20    2
Tall_21    2
Tall_22    1
Tall_23    3
Tall_24    1
Tall_25    4
Tall_26    1
Tall_27    0
Tall_28    2
Tall_29    3
Tall_30    1
Tall_31    2
Tall_32    2
Tall_33    3
Tall_34    3
Tall_35    3
Tall_36    3
Tall_37    2
Tall_38    2
Tall_39    6
Tall_40    0
Tall_41    0
Tall_42    2
Tall_43    2
Tall_44    4
Tall_45    0
Tall_46    2
Tall_47    1
Tall_48    0
dtype: int64